# Generated by Django 5.2.5 on 2025-11-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(max_length=500)),
                ('download_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-download_date'],
            },
        ),
    ]
